### ISSUE TITLE
Suggestion: Add Global CSS styling for all workflows

### ISSUE THREAD

**Issue by iraphaelmary** [Raphaelmary/github-actions-workflow-1#1]
# Global CSS Styling
Add Global CSS styling for all workflows
```css
* {
 margin: 0;
 padding: 0;
 box-sizing: border-box;
}
```
